from projectPractice.ConnThread import ConnThread

def __get_conn_thread() -> ConnThread:...
def db_connect(driver: str, server: str, port: str or int, db: str, user='', password='', autocomm=True) -> None:...
def db_disconnect() -> None:...
def db_read_table(table_name: str) -> list:...
def db_execute_query(query: str) -> list or bool:...
def db_create(db_name: str) -> bool:...
def db_drop(db_name: str) -> bool:...