from projectPractice.ConnThread import ConnThread
from projectPractice.Table import Table

def __get_conn_thread() -> ConnThread:...
def db_connect(driver: str, server: str, port: str or int, db: str, user='', password='', autocomm=True) -> None:...
def db_disconnect() -> None:...
def db_read_table(table: str or Table, limit=int, sql_condition=str, order_by=('', '')) -> list:...
def db_execute_query(query: str) -> list or bool:...
def db_create(db_name: str) -> bool:...
def db_change(db_name: str) -> bool:...
def db_drop(db_name: str) -> bool:...